#!/usr/bin/env python3
"""Stage 29 — Pitch card generator.

Reads the `qualified_leads` view, takes the top N, and for each lead
generates a self-contained markdown card with:
  - Greeting line (uses first name)
  - 3 pain signals (CVE / SSL / outdated / dormant / etc.)
  - Suggested opening line (WhatsApp + cold call versions)
  - Top objection handler
  - WhatsApp deeplink (pre-filled message)
  - Click-to-call tel: link
  - Click-to-email mailto: link

The opener is generated by Claude Haiku via the `claude -p` CLI (Max plan,
no API key). Skips entirely if `claude` is not on PATH.

Output: reports/pitch_cards/<domain>.md, plus an index at
reports/pitch_cards/index.md sorted by lead_score.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib.claude_cli import is_available, run_claude, ClaudeError, extract_json  # noqa: E402
from lib.contacts import open_conn  # noqa: E402
from lib.config import Config, reports_dir  # noqa: E402
from lib.qualified import ensure_view, pain_signals  # noqa: E402
from lib.whatsapp import wa_link, default_opener  # noqa: E402

DB_PATH = reports_dir() / "zwwp.db"
OUT_DIR = reports_dir() / "pitch_cards"


PROMPT_TEMPLATE = """You are writing the opening lines for a WhatsApp outreach
message and a cold-call script for a small-business owner in Zimbabwe. The
goal is to start a brief conversation about fixing a security or performance
issue we observed on their website. Tone: warm, direct, polite, NOT salesy.
Speak as a fellow Zimbabwean ("I noticed", "I'd love to chat", "no pressure
at all"). Keep it short.

Details about the lead:
  Domain        : {domain}
  Business name : {business_name}
  Category      : {category}
  Contact name  : {contact_name}
  Pain signals  :
{pain_bullets}

Output STRICT JSON with these fields and NO other text, NO markdown fences:

{{
  "whatsapp_opener": "<2-3 sentence WhatsApp message — must be under 280 chars>",
  "call_opener": "<the first 2 lines a caller should say on the phone>",
  "talking_points": [
    "<short bullet 1 — the most concrete pain signal>",
    "<short bullet 2 — what we'd actually do to fix>",
    "<short bullet 3 — credibility / urgency cue>"
  ],
  "objection_handler": "<what to say if they brush you off — 1 sentence>",
  "best_time_to_call": "<one of: morning|afternoon|evening>"
}}
"""


def render_card(row: dict, ai: dict, pains: list[str]) -> str:
    """Return the markdown card body for one lead."""
    primary_phone = row.get("phone") or ""
    primary_email = row.get("email_hc") or row.get("email_any") or ""
    name = row.get("display_name") or ""
    first_name = name.split()[0] if name else None
    wa_url = wa_link(primary_phone, ai.get("whatsapp_opener")) if primary_phone else None
    tel = primary_phone.replace(" ", "").replace("-", "") if primary_phone else None
    bullets = "\n".join(f"- {p}" for p in pains) if pains else "- (no specific pain signals — generic pitch)"
    tps = "\n".join(f"- {p}" for p in (ai.get("talking_points") or []))

    md_lines = [
        f"# {row['domain']}",
        "",
        f"**Score:** {row.get('lead_score', '?')} / 100 · "
        f"**Tranco rank:** {row.get('tranco_rank') or '—'} · "
        f"**Category:** {row.get('category') or '—'}",
        "",
        f"**Contact:** {name or '_unknown_'}  ",
        f"**Phone:** `{primary_phone}`" + (f"  — [WhatsApp ↗]({wa_url})" if wa_url else "") +
        (f"  — [call]({'tel:+' + tel})" if tel else ""),
        f"**Email:** `{primary_email}`" + (f"  — [send]({'mailto:' + primary_email})" if primary_email else ""),
        "",
        "## Pain signals",
        bullets,
        "",
        "## WhatsApp opener",
        "",
        f"> {ai.get('whatsapp_opener', '_(generation failed)_')}",
        "",
        "## Cold-call opener",
        "",
        f"> {ai.get('call_opener', '_(generation failed)_')}",
        "",
        "## Talking points",
        tps or "- _(none)_",
        "",
        "## If they brush you off",
        "",
        f"> {ai.get('objection_handler', '_(none)_')}",
        "",
        f"**Best time to call:** {ai.get('best_time_to_call', 'morning')}",
        "",
        "---",
        "",
        "### Site context",
        "",
        f"- WP version: `{row.get('wp_version') or '—'}`",
        f"- Host panel: {row.get('host_panel') or '—'}",
        f"- MX provider: {row.get('mx_provider') or '—'}",
        f"- SSL days remaining: {row.get('ssl_days') if row.get('ssl_days') is not None else '—'}",
        f"- Mobile PageSpeed: {row.get('perf_mobile') if row.get('perf_mobile') is not None else '—'}",
        f"- Last post: `{row.get('last_post_at') or 'unknown'}` ({row.get('posts_last_90d', 0)} in last 90d)",
        f"- Known vulnerabilities: {row.get('vuln_count') or 0}",
        f"- Prior outreach touches: {row.get('prior_touches', 0)}",
        f"- Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
    ]
    return "\n".join(md_lines)


def render_index(rows: list[dict]) -> str:
    lines = [
        "# Pitch cards — qualified ZW cPanel WordPress leads",
        "",
        f"_Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
        f"_Total cards: {len(rows)}_",
        "",
        "Sorted by lead score (higher = better fit). Click into each card "
        "for the WhatsApp opener, cold-call script, and pain signals.",
        "",
        "| # | Domain | Score | Rank | Category | Contact | Pain hooks |",
        "|---|---|---|---|---|---|---|",
    ]
    for i, r in enumerate(rows, 1):
        name = r.get("display_name") or "_unknown_"
        hooks = []
        if r.get("vuln_count"):
            hooks.append(f"{r['vuln_count']} vuln")
        if r.get("ssl_days") is not None and r["ssl_days"] <= 30:
            hooks.append(f"SSL {r['ssl_days']}d")
        if r.get("perf_mobile") is not None and r["perf_mobile"] < 50:
            hooks.append(f"PSI {int(r['perf_mobile'])}")
        if (r.get("wp_version") or "").startswith(("5.", "4.")):
            hooks.append(f"WP {r['wp_version']}")
        hooks.append("CVE-26-41940")
        lines.append(
            f"| {i} | [{r['domain']}](./{r['domain']}.md) | {r.get('lead_score','?')} "
            f"| {r.get('tranco_rank') or '—'} | {r.get('category') or '—'} "
            f"| {name} | {' · '.join(hooks)} |"
        )
    lines.append("")
    return "\n".join(lines)


def build_prompt(row: dict, pains: list[str]) -> str:
    name = row.get("display_name") or "the owner"
    bullets = "\n".join(f"    - {p}" for p in pains) if pains else "    - (none — pitch generically)"
    return PROMPT_TEMPLATE.format(
        domain=row["domain"],
        business_name=row.get("domain", "their business"),
        category=row.get("category") or "small business",
        contact_name=name,
        pain_bullets=bullets,
    )


def run(top_n: int, force: bool) -> int:
    if not is_available():
        print("[pitch] `claude` CLI not on PATH — using fallback openers only",
              file=sys.stderr)
    cfg = Config.from_env()
    conn = open_conn(DB_PATH)
    ensure_view(conn)
    rows = conn.execute("""
        SELECT *
        FROM qualified_leads
        WHERE suppressed=0 AND phone IS NOT NULL AND email_any IS NOT NULL
        ORDER BY lead_score DESC, (tranco_rank IS NULL), tranco_rank
        LIMIT ?
    """, (top_n,)).fetchall()
    rows = [dict(r) for r in rows]
    print(f"[pitch] {len(rows)} qualified leads in scope", file=sys.stderr)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    seen = set()
    if not force:
        seen = {p.stem for p in OUT_DIR.glob("*.md") if p.stem != "index"}
    written_rows: list[dict] = []
    for i, row in enumerate(rows, 1):
        domain = row["domain"]
        if domain in seen:
            written_rows.append(row)
            continue
        pains = pain_signals(row)
        ai = {}
        if is_available():
            try:
                result = run_claude(
                    build_prompt(row, pains),
                    model=cfg.anthropic_model,
                    timeout=90,
                )
                ai = extract_json(result.text) or {}
                if not isinstance(ai, dict):
                    ai = {}
            except (ClaudeError, Exception) as exc:
                print(f"[pitch] {domain} claude error: {exc}", file=sys.stderr)
                ai = {}
        if not ai:
            ai = {
                "whatsapp_opener": default_opener(
                    name=row.get("display_name"),
                    domain=domain,
                    pain=pains[0] if pains else None,
                ),
                "call_opener": default_opener(
                    name=row.get("display_name"),
                    domain=domain,
                    pain=pains[0] if pains else None,
                ),
                "talking_points": pains[:3] or [
                    "Quick free site health check",
                    "Most fixes under $200 — patch + report",
                    "Local, ZW-based, fast turnaround",
                ],
                "objection_handler":
                    "Totally fine — can I send a one-page report on WhatsApp "
                    "and you decide later?",
                "best_time_to_call": "morning",
            }
        card = render_card(row, ai, pains)
        (OUT_DIR / f"{domain}.md").write_text(card, encoding="utf-8")
        written_rows.append(row)
        if i % 10 == 0:
            print(f"[pitch] {i}/{len(rows)} cards written", file=sys.stderr)
    # Re-read full set for index (preserves order)
    (OUT_DIR / "index.md").write_text(render_index(written_rows), encoding="utf-8")
    print(f"[pitch] wrote {len(written_rows)} cards + index to {OUT_DIR}",
          file=sys.stderr)
    return len(written_rows)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--top-n", type=int, default=50,
                   help="how many cards to generate (default 50)")
    p.add_argument("--force", action="store_true")
    args = p.parse_args()
    run(args.top_n, args.force)
    return 0


if __name__ == "__main__":
    sys.exit(main())
